apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: web-service-registry
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: service-registry
    app.kubernetes.io/name: service-registry
    app.openshift.io/runtime: java
  name: web-service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-service-registry
  template:
    metadata:
      labels:
        app: web-service-registry
    spec:
      containers:
      - name: web-service-registry
        imagePullPolicy: Always
        image: image-registry.openshift-image-registry.svc:5000/common-service/web_registry_image:d77fb1dad3eda16fe0245306ed11ed8636c9966d
        ports:
        - containerPort: 8582
          protocol: TCP
